# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

# Riksdag
The Riksdag is the unicameral parliament of Sweden. It consists of 349 members, elected proportionally and serving four-year terms
![Riksdag logo](https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/Riksdag_logo.svg/1920px-Riksdag_logo.svg.png)
## Details

### Name origin
"Riksdag" is a general term for parliament in Swedish.

## Structure

### Leadership
 - Speaker: Andreas Norlen
 - First Deputy Speaker: Kenneth G. Forslund
 - Second Deputy Speaker: Julia Kronlid
 - Third Deputy Speaker: Kerstin Lundgren
 - President by age: Anders Ygeman

### Current seats
|Party Name|Political Group|Seats|
| ---- | ------ | -------|
| Moderate Party | Government | 68 |
| Christian Democrats | Government | 19 |
| Liberals | Government | 16 |
| Sweden Democrats | Confidence and supply | 72 |
| Independent | Confidence and supply | 1 |
| Social Democrats | Opposition | 106 |
| Centre Party | Opposition | 24 |
| Left Party | Opposition | 23 |
| Green Party | Opposition | 18 |
| Independent | Opposition | 2 |

https://www.riksdagen.se/sv/

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [1]:
# make sure to import numpy library
import numpy as np

In [2]:
array_a = np.array([[3,8,-2,3],
                  [.5,-1,6,4],
                  [-5,7,-42,2]
                   ])

array_b = np.array([[42,38,34],
                    [30,26,22],
                    [18,14,10],
                    [6,2,-2],
                    [-6,-10,14]
                   ])

In [3]:
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [4]:
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10,  14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [5]:
for i in range(2):
    array = (array_a, array_b)[i]
    print(["Array A:", "Array B:"][i])
    print("Shape:", array.shape)
    print("Size:", array.size)
    print("nDim:", array.ndim)
    print("nBytes:", array.nbytes)
    print()

Array A:
Shape: (3, 4)
Size: 12
nDim: 2
nBytes: 96

Array B:
Shape: (5, 3)
Size: 15
nDim: 2
nBytes: 120

In [6]:
t_array_a = array_a.transpose()
t_array_b = array_b.transpose()
#array_a + t_array_b
#ValueError: operands could not be broadcast together with shapes (3,4) (3,5) 
t_array_b = np.delete(t_array_b, 4, axis=1)
array_a + t_array_b

array([[ 45. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

To add two arrays, the arrays must be the same shape. One was (3,4), the other was (3,5). By deleting one column of the second array, the arrays become the same shape and therefore can be added to one another.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [7]:
# make sure to import pandas library
import pandas as pd

In [8]:
df = pd.read_csv("train_stations_europe.csv", index_col="id")
df

,name,latitude,longitude,parent_station_id,country,time_zone,is_city,is_main_station,is_airport
id,,,,,,,,,
1,Chateau-Arnoux-St-Auban,44.081790,6.001625,NaN,FR,Europe/Paris,True,False,False
2,Chateau-Arnoux-St-Auban,44.061565,5.997373,1.0,FR,Europe/Paris,False,True,False
3,Chateau-Arnoux Mairie,44.063863,6.011248,1.0,FR,Europe/Paris,False,False,False
4,Digne-les-Bains,44.350000,6.350000,NaN,FR,Europe/Paris,True,False,False
6,Digne-les-Bains,44.088710,6.222982,4.0,FR,Europe/Paris,False,True,False
...,...,...,...,...,...,...,...,...,...
68175,Bari Villaggio del Lavoratore,41.104234,16.822596,NaN,IT,Europe/Rome,False,False,False
68176,Baucca-Garavelle,43.442030,12.250215,NaN,IT,Europe/Rome,False,False,False
68177,Bibbiano Fossa,44.674312,10.478726,NaN,IT,Europe/Rome,False,False,False
68178,Bibbiano Via Monti,44.661871,10.466608,NaN,IT,Europe/Rome,False,False,False
68179,Bivio Barco,44.694544,10.498249,NaN,IT,Europe/Rome,False,False,False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [9]:
df_filtered = df.loc[(df["is_city"]) & (df["country"] == "BE")]
df_filtered

,name,latitude,longitude,parent_station_id,country,time_zone,is_city,is_main_station,is_airport
id,,,,,,,,,
5964,Antwerpen,51.221722,4.405860,NaN,BE,Europe/Brussels,True,False,False
5970,Blandain Ville,50.617431,3.263740,NaN,BE,Europe/Brussels,True,False,False
5974,Bruxelles,50.846520,4.351739,NaN,BE,Europe/Brussels,True,False,False
6003,Quevy Ville,NaN,NaN,NaN,BE,Europe/Brussels,True,False,False
6006,Sterpenich Ville,NaN,NaN,NaN,BE,Europe/Brussels,True,False,False
23044,Liege,50.633333,5.566667,NaN,BE,Europe/Brussels,True,False,False
26863,Gent,51.050000,3.733333,NaN,BE,Europe/Brussels,True,False,False
29328,Bastogne,49.999779,5.709641,NaN,BE,Europe/Brussels,True,False,False
29332,Charleroi,50.410809,4.444643,NaN,BE,Europe/Brussels,True,False,False
32274,Maasmechelen,50.979756,5.701847,NaN,BE,Europe/Brussels,True,False,False
35397,Raeren,50.718089,6.120155,NaN,BE,Europe/Brussels,True,False,False

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.